// src/game/titles/circle-td/content.ts
//
// Track and tile geometry (Task 2, Plan 2): a real, deterministic
// square-spiral board replacing Plan 1's placeholder rectangles (which
// were "the right shape and scale" but not a genuine connected path, and
// whose TILES were a uniform grid over the whole stage rather than
// buildable cells actually tied to the track). This is still not
// final-art geometry — Plan 2's renderer/playtesting may refine the exact
// layout further — but it is a genuine playable board: two independently
// closed spiral loops (one per wave entrance) and a buildable-tile set
// generated by flanking the path, not a full-board grid.
import type { Fx } from "@/game/sim/types";
import { fromInt, mul, div } from "@/game/sim/math/fixed";

export const TARGET_LAND = 1;
export const TARGET_AIR = 2;
export const TARGET_BOTH = 3;

export interface TowerDef {
  name: string; cost: number; targets: number; footprint: number;
  dmg0: number; dmgStep: number; range0: Fx; rangeStep: Fx;
  cooldownTicks: number;          // INVENTED
  slowPct: readonly number[];     // per-level table; [] = tower has no slow effect
  splashRadius0: Fx; splashStep: Fx;
}

const R = (px: number): Fx => fromInt(px);

// Damage/range curves SOURCED (spec §3.4). Cooldowns/splash radii INVENTED.
// `footprint` (multi-cell occupancy for Splash/Damage) is DEFERRED to a
// later task — every tower still occupies exactly the one tile it's
// placed on (see applyCommand in replay.ts); this file only generates
// single tile centres, no multi-cell reservation helper.
export const TOWERS: readonly TowerDef[] = [
  { name: "Fast",   cost: 50,  targets: TARGET_BOTH, footprint: 1,
    dmg0: 9,   dmgStep: 8,   range0: R(150), rangeStep: R(7),
    cooldownTicks: 6,  slowPct: [], splashRadius0: 0, splashStep: 0 },
  { name: "Air",    cost: 45,  targets: TARGET_AIR,  footprint: 1,
    dmg0: 18,  dmgStep: 16,  range0: R(180), rangeStep: R(9),
    cooldownTicks: 12, slowPct: [], splashRadius0: 0, splashStep: 0 },
  { name: "Slow",   cost: 45,  targets: TARGET_BOTH, footprint: 1,
    dmg0: 1,   dmgStep: 0,   range0: R(150), rangeStep: R(7),
    cooldownTicks: 15,
    // SOURCED per-level slow% (original game's exact sequence): +3 for the
    // first 7 steps, then +4, +4 — NOT a uniform step, so it can't be a
    // base+step pair. Must stay a literal table.
    slowPct: [60, 63, 66, 69, 72, 75, 78, 81, 85, 89],
    splashRadius0: 0, splashStep: 0 },
  { name: "Splash", cost: 125, targets: TARGET_LAND, footprint: 2,
    dmg0: 42,  dmgStep: 38,  range0: R(100), rangeStep: R(5),
    cooldownTicks: 30, slowPct: [], splashRadius0: R(40), splashStep: R(2) },
  { name: "Damage", cost: 260, targets: TARGET_LAND, footprint: 3,
    dmg0: 250, dmgStep: 227, range0: R(125), rangeStep: R(6),
    cooldownTicks: 60, slowPct: [], splashRadius0: 0, splashStep: 0 },
];

export const WAVE_SIZE = 30;             // SOURCED (15 per entrance × 2)
export const WAVE_INTERVAL_TICKS = 600;  // 20 s × 30 Hz  (interval SOURCED)
// START_BANK restored to the SOURCED 125 (was 250 INVENTED under Plan 1's
// placeholder geometry) — confirmed 2026-09-19 winnable-and-climbing on the
// real spiral geometry once paired with the by-maxHp bounty fix and
// GAMMA=5 (see balance.ts and docs/superpowers/2026-09-18-circle-td-balance-tuning.md
// "Real-geometry re-tune"). This resolves the Plan-2 P3 fidelity decision in
// favor of the faithful value — no INVENTED bank figure needed after all.
export const START_BANK = 125;           // SOURCED
export const ALIVE_CAP_NORMAL = 100;     // SOURCED
export const SELL_REFUND_PCT = 75;       // SOURCED

// --- Coordinate space ---
// Stage pixels, origin top-left, +x right, +y down. This is the shared
// space the sim, the (future) Canvas2D renderer, and input hit-testing all
// use — nothing here is normalized/relative.
export const STAGE_W = 840;
export const STAGE_H = 680;
export const TILE_SIZE = 32; // px — buildable-tile footprint, and the pitch
                              // the flanking-tile generator samples along
                              // each path segment.

// --- Track: real square-spiral polylines ---
// Each poly is [x0,y0, x1,y1, ...] in Q16.16, implicitly closed
// (posAt/trackLength wrap the last point back to the first). Built by
// buildSpiralPoints() below in plain stage-px integers, then scaled to Fx.
//
// EVERY segment — including the corridor that closes the loop — is
// strictly horizontal or vertical by construction, so segLen()'s Manhattan
// sum below is always exactly the Euclidean length. Plan 1's placeholder
// had diagonal ring-to-ring and closing edges (ruling R5) that needed a
// "Manhattan, not Euclidean, and that's intentional" caveat; the real
// spiral has no such case to special-case.
//
// buildSpiralPoints traces concentric rectangles inward — top edge, right
// edge, bottom edge, then partway up the left edge (stopping `inset` short
// of the top so a gap is left for the next ring to open into) — steps the
// whole rectangle inward by `inset` on every side, and repeats until the
// remaining rectangle is too small to leave room for a flanking tile lane.
// It then draws that final (small) rectangle in full and closes the loop
// with an explicit corridor: straight down below the whole spiral, left,
// straight up outside the spiral's own left edge, then right back to the
// exact starting point. That corridor crosses the outermost ring's bottom
// edge exactly once (a single-point bridge crossing, not an overlapping
// retrace) and is otherwise routed through stage margin no ring touches.
// The corridor's last point is an exact duplicate of the first point, so
// the implicit closing edge trackLength/posAt would otherwise walk is
// zero-length — never a shortcut across the board.
function buildSpiralPoints(
  x0: number, y0: number, x1: number, y1: number, inset: number, margin: number
): number[] {
  const pts: number[] = [];
  let left = x0, top = y0, right = x1, bottom = y1;
  pts.push(left, top);
  while (
    right - left > 2 * inset + TILE_SIZE * 4 &&
    bottom - top > 2 * inset + TILE_SIZE * 4
  ) {
    pts.push(right, top);
    pts.push(right, bottom);
    pts.push(left, bottom);
    pts.push(left, top + inset);
    left += inset; top += inset; right -= inset; bottom -= inset;
    pts.push(left, top);
  }
  pts.push(right, top);
  pts.push(right, bottom);
  pts.push(left, bottom);
  const endX = left;
  pts.push(endX, y1 + margin);
  pts.push(x0 - margin, y1 + margin);
  pts.push(x0 - margin, y0);
  pts.push(x0, y0); // == pts[0], pts[1] — zero-length wrap edge
  return pts;
}

const toFx = (pts: readonly number[]): Int32Array => {
  const out = new Int32Array(pts.length);
  for (let i = 0; i < pts.length; i++) out[i] = fromInt(pts[i]);
  return out;
};

// Two independently closed loops, one per wave entrance (same contract as
// Plan 1's TRACK.outer/TRACK.inner) — outer is the larger/longer lap,
// inner nests inside it near the board's centre, matching the original
// two-entrance intent.
const OUTER_PTS = buildSpiralPoints(60, 60, 780, 620, 90, 40);
const INNER_PTS = buildSpiralPoints(200, 200, 640, 480, 55, 30);

export const TRACK = {
  outer: toFx(OUTER_PTS),
  inner: toFx(INNER_PTS),
};

export const trackLength = (poly: Int32Array): Fx => {
  let len = 0;
  const n = poly.length / 2;
  for (let i = 0; i < n; i++) {
    const j = (i + 1) % n;
    len += segLen(poly[i * 2], poly[i * 2 + 1], poly[j * 2], poly[j * 2 + 1]);
  }
  return len;
};

const segLen = (x0: Fx, y0: Fx, x1: Fx, y1: Fx): Fx => {
  const dx = x1 - x0, dy = y1 - y0;
  // Every segment is axis-aligned by construction, so Manhattan == Euclidean.
  return Math.abs(dx) + Math.abs(dy);
};

export const posAt = (poly: Int32Array, dist: Fx): { x: Fx; y: Fx } => {
  const total = trackLength(poly);
  let d = ((dist % total) + total) % total;
  const n = poly.length / 2;
  for (let i = 0; i < n; i++) {
    const j = (i + 1) % n;
    const x0 = poly[i * 2], y0 = poly[i * 2 + 1];
    const x1 = poly[j * 2], y1 = poly[j * 2 + 1];
    const L = segLen(x0, y0, x1, y1);
    if (d <= L || i === n - 1) {
      const t = L === 0 ? 0 : div(d, L); // fraction along segment, Q16.16
      return { x: x0 + mul(x1 - x0, t), y: y0 + mul(y1 - y0, t) };
    }
    d -= L;
  }
  return { x: poly[0], y: poly[1] };
};

// --- Buildable tiles: cells flanking both tracks ---
// Per Task 2's brief: buildable tiles are the cells immediately flanking
// each path segment on both sides (the original's "raised ground around
// the paths"), not a grid covering the whole stage. Generated
// deterministically in plain stage-px integers, then scaled to Fx.

type Seg = readonly [number, number, number, number];

function segmentsOf(pts: readonly number[]): Seg[] {
  const segs: Seg[] = [];
  const n = pts.length / 2;
  for (let i = 0; i < n - 1; i++) {
    const x0 = pts[i * 2], y0 = pts[i * 2 + 1];
    const x1 = pts[(i + 1) * 2], y1 = pts[(i + 1) * 2 + 1];
    if (x0 === x1 && y0 === y1) continue; // the zero-length wrap-closing edge
    segs.push([x0, y0, x1, y1]);
  }
  return segs;
}

// Squared distance from a point to an axis-aligned segment (every track
// segment is one or the other by construction).
const pointSegDistSq = (px: number, py: number, x0: number, y0: number, x1: number, y1: number): number => {
  if (y0 === y1) {
    const lo = Math.min(x0, x1), hi = Math.max(x0, x1);
    const cx = px < lo ? lo : px > hi ? hi : px;
    const dx = px - cx, dy = py - y0;
    return dx * dx + dy * dy;
  }
  const lo = Math.min(y0, y1), hi = Math.max(y0, y1);
  const cy = py < lo ? lo : py > hi ? hi : py;
  const dx = px - x0, dy = py - cy;
  return dx * dx + dy * dy;
};

const minDistSqToTracks = (px: number, py: number, segs: readonly Seg[]): number => {
  let best = Infinity;
  for (const [x0, y0, x1, y1] of segs) {
    const d = pointSegDistSq(px, py, x0, y0, x1, y1);
    if (d < best) best = d;
  }
  return best;
};

// Tile-centre distance from a segment's centreline — one tile-width out,
// so a tile's own near edge sits right against the path.
const FLANK_OFFSET = TILE_SIZE;
// Minimum clearance a candidate must keep from EVERY track segment (not
// just the one it was generated to flank) to avoid landing on the path
// near a corner, or in the narrow band between the two nested tracks.
const MIN_CLEARANCE = Math.trunc(TILE_SIZE * 0.75);

// One candidate per TILE_SIZE step along a segment, offset FLANK_OFFSET to
// both sides — "the cells immediately flanking each path segment on both
// sides" (Task 2 brief).
function flankCandidates(segs: readonly Seg[]): Array<readonly [number, number]> {
  const out: Array<readonly [number, number]> = [];
  for (const [x0, y0, x1, y1] of segs) {
    const horiz = y0 === y1;
    const len = horiz ? Math.abs(x1 - x0) : Math.abs(y1 - y0);
    const dirX = horiz ? (x1 > x0 ? 1 : -1) : 0;
    const dirY = horiz ? 0 : (y1 > y0 ? 1 : -1);
    for (let d = 0; d <= len; d += TILE_SIZE) {
      const sx = x0 + dirX * d, sy = y0 + dirY * d;
      if (horiz) {
        out.push([sx, sy - FLANK_OFFSET]);
        out.push([sx, sy + FLANK_OFFSET]);
      } else {
        out.push([sx - FLANK_OFFSET, sy]);
        out.push([sx + FLANK_OFFSET, sy]);
      }
    }
  }
  return out;
}

function buildTiles(): number[] {
  const outerSegs = segmentsOf(OUTER_PTS);
  const innerSegs = segmentsOf(INNER_PTS);
  const allSegs = [...outerSegs, ...innerSegs];
  const candidates = [...flankCandidates(outerSegs), ...flankCandidates(innerSegs)];
  const minClearSq = MIN_CLEARANCE * MIN_CLEARANCE;
  const seen = new Set<number>();
  const tiles: number[] = [];
  for (const [x, y] of candidates) {
    if (x < 0 || y < 0 || x > STAGE_W || y > STAGE_H) continue; // stay on-stage
    if (minDistSqToTracks(x, y, allSegs) < minClearSq) continue; // never on the path
    // Dedup near-identical candidates (two segments' flank zones meeting at
    // a corner) onto a coarse half-tile grid.
    const gx = Math.floor(x / (TILE_SIZE / 2));
    const gy = Math.floor(y / (TILE_SIZE / 2));
    const key = gx * 1_000_000 + gy;
    if (seen.has(key)) continue;
    seen.add(key);
    tiles.push(x, y);
  }
  return tiles;
}

export const TILES = toFx(buildTiles());
export const TILE_COUNT = TILES.length / 2;
