// src/game/test/determinism.test.ts
//
// The golden determinism gate: a scripted replay's hash/score/wave are pinned
// to a committed fixture. This test file (not replay.ts itself) is allowed to
// touch node:fs — it's a *.test.ts, excluded from the purity guard's scan.
//
// 2026-09-19 refactor: the replay's command list is now GENERATED by a
// deterministic in-file strategy (buildGoldenReplay) instead of a hand-listed
// tick script. The old hand-listed ticks had to be regenerated by hand every
// time geometry or a balance constant changed (three times already: Plan 1
// placeholder -> real spiral -> nested loops -> open-area grid + hard economy)
// and were the single most fragile part of this suite. The generator drives a
// fresh sim with a fixed strong-play strategy and records only EFFECTIVE
// commands, so the tile indices AND the ticks flow through automatically from
// the current geometry/economy; only the golden HASH is re-pinned by hand
// (UPDATE_GOLDEN=1) when sim behaviour intentionally changes. The gate still
// does its job: same code -> same generated replay -> same hash; an unintended
// sim-behaviour change shifts the hash and fails loud.
import { describe, it, expect } from "vitest";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { applyCommand, runReplay, upgradeCost, type Command, type Replay } from "@/game/sim/replay";
import { SIM_VERSION } from "@/game/sim/types";
import { makeSim } from "@/game/titles/circle-td";
import { circleTdTitle } from "@/game/titles/circle-td/title";
import { TILES, TILE_COUNT, TOWERS, TRACK, trackLength, posAt } from "@/game/titles/circle-td/content";
import { towerRangeSq } from "@/game/titles/circle-td/rules";
import { mul, fromInt } from "@/game/sim/math/fixed";

const FIXTURE = join("src/game/test/determinism.golden.json");

// Tile indices within a Damage(L0) tower's range of some sampled point on
// either track polyline — the same method balance.sweep.test.ts's own
// inRangeTiles() uses. Recomputed here rather than hardcoding raw tile
// numbers: content.ts's geometry can (and does) change, and a hardcoded index
// could silently drift out of range on the next change.
function inRangeTiles(): number[] {
  const rSq = towerRangeSq(4, 0);
  const step = fromInt(8); // sample the track every ~8px
  const out: number[] = [];
  for (let ti = 0; ti < TILE_COUNT; ti++) {
    const tx = TILES[ti * 2], ty = TILES[ti * 2 + 1];
    let near = false;
    for (const poly of [TRACK.outer, TRACK.inner]) {
      const total = trackLength(poly);
      for (let d = 0; d <= total && !near; d += step) {
        const p = posAt(poly, d);
        const dx = p.x - tx, dy = p.y - ty;
        if (mul(dx, dx) + mul(dy, dy) <= rSq) near = true;
      }
    }
    if (near) out.push(ti);
  }
  return out;
}

const IN_RANGE = inRangeTiles();
const SEED = 20260918;
const MODE = "daily" as const;

// Best-affordable buy order (strongest first), matching balance.sweep's own
// realistic-opening strategy. Costs/ids from content.ts (Fast=0 Air=1 Slow=2
// Splash=3 Damage=4).
const AFFORD: ReadonlyArray<{ type: number; cost: number }> = [
  { type: 4, cost: TOWERS[4].cost },
  { type: 3, cost: TOWERS[3].cost },
  { type: 0, cost: TOWERS[0].cost },
  { type: 1, cost: TOWERS[1].cost },
  { type: 2, cost: TOWERS[2].cost },
];

// Bound the generated log so the fixture stays modest: place at most this many
// towers, and stop generating once this wave is reached (runReplay then keeps
// ticking the built defense to gameOver, so the hash still reflects a full
// run to death). Both are comfortably inside "winnable" for the tuned economy
// (full strong play dies ~wave 155; a 40-tower defense dies ~wave 64-75), so
// the inertness self-checks below (wave >= 20) always hold.
const GOLDEN_TOWERS = 40;
const GOLDEN_STOP_WAVE = 30;
const GOLDEN_TICK_CEILING = 300_000;

// Deterministic strong-play strategy, recording only EFFECTIVE commands (state
// actually changed after applyCommand) — so the log is exactly "what
// happened", the log a leaderboard replay must reproduce. Each tick, the first
// applicable action:
//   1. place the next in-range tile with the best currently-affordable tower;
//   2. once towers exist, do a one-off place+sell of a throwaway tile (so the
//      "sell" path is exercised);
//   3. otherwise upgrade the lowest-level tower whose next upgrade is affordable
// (so upgrades interleave from early on — maxTowerLevel is never 0). Runs until
// GOLDEN_STOP_WAVE / gameOver / the tick ceiling.
function buildGoldenReplay(): Replay {
  const sim = makeSim({ seed: SEED, mode: MODE });
  const s = sim.state;
  const tiles = IN_RANGE;
  const commands: Command[] = [];
  const cap = Math.min(tiles.length, GOLDEN_TOWERS);
  const throwawayTile = tiles[Math.min(tiles.length - 1, Math.floor(tiles.length * 0.85))];
  let next = 0;
  let didThrowaway = false;

  while (!s.gameOver && s.wave < GOLDEN_STOP_WAVE && s.tick < GOLDEN_TICK_CEILING) {
    let acted = false;

    if (next < cap) {
      const pick = AFFORD.find((t) => s.bank >= t.cost);
      if (pick) {
        const before = s.towers.count;
        const cmd: Command = { tick: s.tick, type: "place", tower: pick.type, tile: tiles[next] };
        applyCommand(s, cmd);
        if (s.towers.count > before) { commands.push(cmd); next++; acted = true; }
      }
    }

    if (!acted && !didThrowaway && s.towers.count > 0) {
      const buy: Command = { tick: s.tick, type: "place", tower: 0, tile: throwawayTile };
      const before = s.towers.count;
      applyCommand(s, buy);
      if (s.towers.count > before) {
        commands.push(buy);
        const sell: Command = { tick: s.tick, type: "sell", tile: throwawayTile };
        applyCommand(s, sell);
        commands.push(sell);
        didThrowaway = true;
        acted = true;
      }
    }

    if (!acted) {
      const t = s.towers;
      let bi = -1, bl = 99;
      for (let i = 0; i < t.count; i++) {
        const lv = t.level[i];
        if (lv < 9 && lv < bl && s.bank >= upgradeCost(TOWERS[t.type[i]].cost, lv)) { bl = lv; bi = i; }
      }
      if (bi !== -1) {
        const cmd: Command = { tick: s.tick, type: "upgrade", tile: t.tile[bi] };
        const before = t.level[bi];
        applyCommand(s, cmd);
        if (t.level[bi] > before) commands.push(cmd);
      }
    }

    sim.tick();
  }

  return { seed: SEED, simVersion: SIM_VERSION, mode: MODE, commands };
}

describe("determinism golden gate", () => {
  it("plays a real defense (kills, upgrades, a sell) and reproduces the committed hash", () => {
    const replay = buildGoldenReplay();
    const result = runReplay(replay, circleTdTitle);

    // Inertness self-checks — run unconditionally, including in UPDATE_GOLDEN=1
    // regeneration mode, so a future edit that accidentally makes this replay
    // inert (placements drifting onto occupied/out-of-range tiles, an economy
    // so harsh nothing survives) fails loud instead of quietly re-pinning a
    // zero-kill fixture.
    expect(result.score).toBeGreaterThan(0);
    expect(result.wave).toBeGreaterThanOrEqual(20);
    expect(result.maxTowerLevel).toBeGreaterThan(0);
    // The generator must actually have exercised place + sell + upgrade.
    expect(replay.commands.some((c) => c.type === "place")).toBe(true);
    expect(replay.commands.some((c) => c.type === "sell")).toBe(true);
    expect(replay.commands.some((c) => c.type === "upgrade")).toBe(true);

    if (process.env.UPDATE_GOLDEN === "1") {
      writeFileSync(FIXTURE, JSON.stringify({ replay, ...result }, null, 2) + "\n");
      // eslint-disable-next-line no-console
      console.warn("golden fixture written — inspect and commit it");
    } else if (!existsSync(FIXTURE)) {
      throw new Error(
        `Golden fixture missing at ${FIXTURE}. Run ` +
          "`UPDATE_GOLDEN=1 npx vitest run src/game/test/determinism.test.ts`, " +
          "inspect the result (score > 0, wave >= 20, maxTowerLevel > 0), then commit the fixture."
      );
    }

    const golden = JSON.parse(readFileSync(FIXTURE, "utf8"));
    expect(result.hash).toBe(golden.hash);
    expect(result.score).toBe(golden.score);
    expect(result.wave).toBe(golden.wave);
  });
});
